"""Extend green original player-ticket witness with pet owner and 3-slot overflow.

All subsequent events use the SAME genuine item index3 freshly generated by
original ENEMY_createEnemy -> ITEM_makeItemAndRegist. No source gameplay body
is replaced. The source-defined configuration getFdnum=2 adapter is retained.
"""
from __future__ import annotations
from tools import stoneage_battle_original_drop_ticket_audit as ticket
from tools import stoneage_party_pet_original_attack_audit as attack

replace_once=ticket.replace_once

MORE=r"""
 /* Reset to exact post-spawn player-ticket baseline for each independent case.
    Neither the original ITEM allocator nor the original actor sequence is rewound. */
 for(int scenario=0;scenario<3;scenario++){
  memcpy(reward_items,ticket_saved_items,sizeof ticket_saved_items);
  memcpy(slots,ticket_saved_actors,sizeof ticket_saved_actors);
  *arena=ticket_saved_arena;ITEM_COUNT=ticket_saved_use;
  arena->use=1;arena->Side[0].type=BATTLE_S_TYPE_PLAYER;
  arena->Side[1].type=BATTLE_S_TYPE_ENEMY;
  for(int j=0;j<BATTLE_ENTRY_MAX;j++)arena->Side[1].Entry[j].ENTRY_FIELD=-1;
  arena->Side[1].Entry[0].ENTRY_FIELD=positive_actor;
  arena->Side[0].Entry[0].ENTRY_FIELD=0;
  for(int j=0;j<GETITEM_MAX;j++)arena->Side[0].Entry[0].getitem[j]=-1;
  slots[positive_actor].data[CHAR_HP]=0;
  CHAR_setFlg(positive_actor,CHAR_ISDIE,FALSE);
  int lists[2]={scenario==0?5:0,-1};
  if(scenario==0){
   arena->Side[0].Entry[5].ENTRY_FIELD=2;
   demand(CHAR_CHECKINDEX(2)&&CHAR_getInt(2,CHAR_WHICHTYPE)==CHAR_TYPEPET,
          "original actor2 is actual participating pet");
   demand(BATTLE_No2Index(battle_at,5)==2,
          "original pet attack-list battle ticket resolves the pet actor");
  }else{
   for(int j=0;j<3;j++){
    int id=240+j;
    arena->Side[0].Entry[0].getitem[j]=id;
    reward_items[id].use=1;
    reward_items[id].ITEM_FIELD.data[ITEM_ID]=900+j;
    reward_items[id].ITEM_FIELD.workint[ITEM_WORKCHARAINDEX]=-1;
    reward_items[id].ITEM_FIELD.workint[ITEM_WORKOBJINDEX]=-1;
    ITEM_COUNT++;
   }
  }
  ITEM_TYPE current_pool[256],expected_pool[256];
  memcpy(current_pool,reward_items,sizeof current_pool);
  memcpy(expected_pool,current_pool,sizeof expected_pool);
  int current_count=ITEM_COUNT;
  BATTLE expected_arena=*arena;
  Char current_actors[7];memcpy(current_actors,slots,sizeof current_actors);
  int expected_draws;
  if(scenario==0){
   expected_arena.Side[0].Entry[0].getitem[0]=3;
   expected_draws=1;
  }else if(scenario==1){
   expected_pool[3].use=0;expected_draws=2;
  }else{
   expected_arena.Side[0].Entry[0].getitem[1]=3;
   expected_pool[241].use=0;expected_draws=3;
  }
  rng_mode=scenario==2?1:0;rng_count=0;
  int result=BATTLE_AddExpItem(battle_at,lists);
  demand(result==0,"real original AddExpItem overflow or pet ticket returns success");
  demand(rng_count==expected_draws,
         "original recipient RAND and overflow replacement/discard RAND cardinality");
  demand(!memcmp(&expected_arena,arena,sizeof expected_arena),
         "complete battle arena exact pending three-slot and owner redirect oracle");
  demand(!memcmp(expected_pool,reward_items,sizeof expected_pool),
         "all 256 item records exact original overflow release/retain oracle");
  demand(ITEM_COUNT==current_count-(scenario!=0),
         "item counter decremented only on original three-slot overflow release");
  demand(slots[positive_actor].indexOfExistItems[CHAR_STARTITEMARRAY]==-1,
         "enemy carried slot cleared for original pet and both overflow cases");
  demand(CHAR_getFlg(positive_actor,CHAR_ISDIE)==TRUE&&
         slots[positive_actor].data[CHAR_DEADCOUNT]==current_actors[positive_actor].data[CHAR_DEADCOUNT]+1,
         "original enemy death flag/count exact on each independent reward case");
  demand(slots[scenario==0?2:0].data[CHAR_KILLPETCOUNT]==
         current_actors[scenario==0?2:0].data[CHAR_KILLPETCOUNT]+1,
         "original EXP/kill count to attacker, pending loot to owner for pet");
  for(int i=0;i<7;i++)if(i!=positive_actor&&i!=(scenario==0?2:0))
   demand(!memcmp(&current_actors[i],&slots[i],sizeof(Char)),
          "all other original actors byte identical even for pet ticket");
  printf("REAL_HEADER_DROP_BUFFER|scenario=%d|pet_ticket=%d|pending0=%d|pending1=%d|pending2=%d|discarded_new=%d|replaced_old=%d|rand_calls=%d|pool_count=%d|whole_arena_oracle=1|whole_pool_oracle=1|whole_other_actors_oracle=1\n",
         scenario,scenario==0,
         arena->Side[0].Entry[0].getitem[0],
         arena->Side[0].Entry[0].getitem[1],
         arena->Side[0].Entry[0].getitem[2],
         scenario==1,scenario==2,rng_count,ITEM_COUNT);
 }
"""

def extended_controls(profile):
    return ticket.drop.factory.allocator.item.substitutions(profile,MORE).replace(
        "ENTRY_FIELD","char_index" if profile=="bismarck" else "charaindex")

def buffer_native(profile,source,battle,event,root):
    native,has_lua=ticket.ticket_native(profile,source,battle,event,root)
    prior=ticket.ticket_controls(profile)
    restoration=" memcpy(reward_items,ticket_saved_items,sizeof ticket_saved_items);"
    if prior.count(restoration)!=1:
        raise ValueError("ticket restoration anchor drift")
    enriched=prior.replace(restoration,extended_controls(profile)+"\n"+restoration,1)
    native=replace_once(native,prior,enriched)
    return native,has_lua

def main():
    attack.main(native_builder=buffer_native,extra_markers=(
        "REAL_HEADER_FINISH_DISPATCH|","FINISH_RS_OBS|",
        "REAL_HEADER_ITEM_FACTORY|","REAL_HEADER_ENEMY_POSITIVE_DROP|",
        "REAL_HEADER_DROP_TICKET|","REAL_HEADER_DROP_BUFFER|"))
    print("BOUNDARY|real original attacker list pet redirect/3 pending slots original destroy or replace with synthetic pending 240..242; no actual Finish transfer of newly spawned item, early original historical equivalence unproven")
    print("RESOLUTION|ORIGINAL_REAL_HEADER_DROP_BUFFER_BOUNDED_PASS")

if __name__=="__main__":main()
